name: Conventional Commits

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  commitsar:
    name: Validate for conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            buildprops:
              - 'Directory.Build.props'
      - name: Publish
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/Meeting.Wpf/Meeting.Wpf.csproj
          VERSION_FILE_PATH: src/Directory.Build.props
          TAG_COMMIT: false
