name: Conventional Commits

on:
  push:
  pull_request:
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  commitsar:
    name: Validate for conventional commits
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run commitsar
